docker-compose-yaml: ./lagoon-docker-compose.yml

project: %projectName%


tasks:
  post-rollout:
    - run:
        name: Prepare storage
        command: mkdir -p /app/storage/framework/sessions /app/storage/framework/views /app/storage/framework/cache /app/storage/framework/cache/data
        service: cli
        shell: bash
    - run:
        name: Run migrations
        command: php artisan -n migrate --force
        service: cli
        shell: bash
